<?php

namespace backend\controllers;

use common\components\Debugger as d;
use common\models\Clients;
use shadow\helpers\CryptoHelper;

class ClientsController extends MainController
{
    public function init()
    {
//        d::pre(CryptoHelper::createBearerToken());
        $this->model = new Clients();
        parent::init(); // TODO: Change the autogenerated stub
    }

}//Class
