<?php

namespace api\controllers;

use api\components\api\Api;
use api\components\api\CException;
use common\components\Debugger as d;
use Yii;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\Controller;

class MainController extends Controller
{
    /** @var Api $api */
    public $api = null;
    public $notFound404 = '404 not found';

    /**
     * @throws CException
     */
    public function init()
    {
//        d::ajax($_SERVER);
        parent::init(); // TODO: Change the autogenerated stub
//        d::ajax(Yii::$app->request->userIP);
        $this->api = new Api(Yii::$app->params['token']);
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator'] = [
            'class' => \yii\filters\ContentNegotiator::className(),
            'formats' => [
                'application/json' => \yii\web\Response::FORMAT_JSON,
            ],
        ];
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::class,
        ];
        return $behaviors;
    }

}//Class
