<?php

namespace backend\components\helpers;

use backend\controllers\MainController;
use common\components\Debugger as d;
use Yii;
use yii\web\Controller;

class Html extends \yii\bootstrap5\Html
{

    public static function img($src, $options = []): string
    {
        /** @var MainController $controller */
        $controller = Yii::$app->controller;
        $baseUrl = $controller->AppAsset->baseUrl;
        $src = $baseUrl . '/dist/' . $src;
        return parent::img($src, $options); // TODO: Change the autogenerated stub
    }

}//Class
