<?php
namespace shadow;

use backend\models\Settings;
use yii\base\Component;

class SSettings extends Component
{
    private $_settings = [];
    private $_settings_objects = [];
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function get($key, $default = '')
    {
        if (!$this->_settings) {
            $this->_settings = $this->loadSettings();
        }
        if (isset($this->_settings[$key])) {
            return $this->_settings[$key];
        } else {
            return $default;
        }
    }
    public function loadSettings()
    {
        /**
         * @var $settings Settings[]
         */
        $result = \Yii::$app->cache->get('settings_cache');
        if (!$result) {
            $settings = Settings::find()->indexBy('key')->all();
            foreach ($settings as $key => $val) {
                $result[$key] = $val->value;
            }
            \Yii::$app->cache->set('settings_cache', $result);
        }
        return $result;
    }

    public function getObject($key)
    {
        if (count($this->_settings_objects) == 0) {
            $this->_settings_objects = $this->loadSettingsObjects();
        }
        if (isset($this->_settings_objects[$key])) {
            return $this->_settings_objects[$key];
        } else {
            return NULL;
        }
    }
    public function loadSettingsObjects()
    {
        $result = [];
        /**
         * @var $settings Settings[]
         */
        $settings = Settings::find()->indexBy('key')->all();
        foreach ($settings as $key => $val) {
            $result[$key] = $val;
        }
        return $result;
    }
}
